{% set name = "scicookie" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scicookie-{{ version }}.tar.gz
  sha256: 42543b9703123eccc154a8e3af82faaa24316517d808b72ab5fe867243dd3d9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.1,<3.12
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<3.12
    - cookieninja >=1.0.0
    - sh >=2.0.4,<3.0.0
    - __unix     # [unix]
    - colorama >=0.4.6,<0.5.0
    - inquirer >=3.1.3,<4.0.0
    - pyyaml >=6.0.1
    - jinja2 >=3.1.2

test:
  imports:
    - scicookie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://osl-incubator.github.io/scicookie
  summary: Cookiecutter template for a Python package
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ayeankit
    - xmnlab
