{% set name = "scicookie" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scicookie-{{ version }}.tar.gz
  sha256: a7e7e1a33fb581e23048a29b4ce4b5f1ecbe37325dbdf4a36dc3eb9eee300306

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.1,<4
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<3.12
    - cookiecutter 2.6.0
    - colorama >=0.4.6
    - inquirer >=3.1.3
    - pyyaml >=6.0.1
    - jinja2 >=3.1.2
    - nodejs >=20.13.0
    - pre-commit-hooks >=0.4.6

test:
  imports:
    - scicookie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://osl-incubator.github.io/scicookie
  summary: Cookiecutter template for a Python package
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ayeankit
    - xmnlab
