{% set name = "scicookie" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scicookie-{{ version }}.tar.gz
  sha256: f8d26f50b8e49c05949d90f50703d1747585f0a1e40116c321acefb2347399c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.1,<4
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<3.12
    - cookiecutter 2.6.0
    - colorama >=0.4.6
    - inquirer >=3.1.3
    - pyyaml >=6.0.1
    - jinja2 >=3.1.2
    - nodejs >=20.12.0
    - pre-commit-hooks >=0.4.6

test:
  imports:
    - scicookie
  commands:
    # note: pip check will fail because instead of using nodejs-wheel, we use here just nodejs
    # - pip check
    - command -v scicookie
  requires:
    - pip

about:
  home: https://osl-incubator.github.io/scicookie
  summary: Cookiecutter template for a Python package
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - ayeankit
    - xmnlab
